language: node_js
node_js:
<<<<<<< HEAD
  - "4.8.0"
script: npm run $COMMAND
env:
  - COMMAND=test
=======
  - "0.10"
>>>>>>> v2
notifications:
  irc:
    channels:
      - "chat.freenode.net#montage"
    on_success: false
    template:
      - "%{author} broke the %{repository} tests on %{branch}: %{build_url}"
